scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['13.201.167.137:9100']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['13.201.167.137:8080']
